services:
  postgres:
    image: postgres:17
    container_name: audit_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - audit_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7
    container_name: audit_redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

  fastapi:
    build: .
    container_name: audit_service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      RUNNING_IN_DOCKER: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  audit_data:
